# Frontend Bygg-steg

FROM node:22-alpine AS build

# skapa work directory-mapp
WORKDIR /app

#kopiera package-filer
COPY package.json package-lock.json ./
# installera dependancies mm.
RUN npm ci

# kopiera filer
COPY . .
RUN npm run build
# -----------------------------------------

# Frontend runtime
FROM nginx:1.27-alpine AS runtime

# Skapa användare
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

COPY --from=build /app/dist /usr/share/nginx/html

# sätt rättigheter på mappen.
RUN chown -R appuser:appgroup /usr/share/nginx/html
RUN chown -R appuser:appgroup /var/cache/nginx 
RUN chown -R appuser:appgroup /run 
RUN chown -R appuser:appgroup /var/run

ARG APP_VERSION=dev
ENV APP_VERSION=$APP_VERSION

# kör appen
USER appuser

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
