# API Bygg-steg

FROM node:22-alpine AS build

# skapa work directory-mapp
WORKDIR /app

#kopiera package-filer
COPY package.json package-lock.json ./

# installera dependancies mm.
RUN npm ci

# kopiera filer
COPY . .

RUN npm run build
# -----------------------------------------

# API runtime
FROM node:22-alpine AS runtime

# Skapa användare, sätt rättigheter
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# kopiera filer (dist)
WORKDIR /app

COPY --from=build --chown=appuser:appgroup /app/node_modules ./node_modules
COPY --from=build --chown=appuser:appgroup /app/dist ./dist
COPY --from=build --chown=appuser:appgroup /app/package.json ./

RUN mkdir -p data && chown appuser:appgroup data && chmod 755 data

ARG APP_VERSION=dev
ENV APP_VERSION=$APP_VERSION

# kör appen
USER appuser

EXPOSE 3001
CMD ["node", "dist/index.js"]